const express = require("express")
const bodyParser = require("body-parser")
const cors = require("cors")
const morgan = require("morgan")
const server = express()
const SqlAccount = require("./SqlAccount")
const SqlProduct = require("./SqlProduct")
const SqlCoupon = require("./SqlCoupon")
const SqlOrderList = require("./SqlOrderList")
const SqlCart = require("./SqlCart")
const SqlPayment = require("./SqlPayment")

server.use(morgan("combined"))
server.use(bodyParser.json())
server.use(cors())
server.use("/shop",SqlAccount)
server.use("/shop",SqlProduct)
server.use("/shop",SqlCoupon)
server.use("/shop",SqlOrderList)
server.use("/shop",SqlCart)
server.use("/shop",SqlPayment)

server.listen(process.env.PORT || 8088)